all: Arithmetic Logic Shifts

Arithmetic: arithmetic.s
	gcc arithmetic.s -g -o arithmetic

Logic: logic.s
	gcc logic.s -g -o logic

Shifts: shifts.s
	gcc shifts.s -g -o shifts

clean:
	rm arithmetic logic shifts
	
