all: FtoC CtoF toNegative toInches TenTimes

FtoC: FtoC.s
	gcc FtoC.s -g -o FtoC

CtoF: CtoF.s
	gcc CtoF.s -g -o CtoF

toNegative:
	gcc toNegative.s -g -o toNegative

toInches:
	gcc toInches.s -g -o toInches

TenTimes:
	gcc TenTimes.s -g -o TenTimes

clean:
	rm FtoC CtoF toNegative toInches TenTimes

